const orderHistory = [
  {
    orderNumber: '114-3941689-8772232',
    orderTotal: 34.0,
    orderShipTo: 'JS Masher',
    orderDate: 'August 4, 2020',
    orderDelivered: 'August 8, 2020',
    orderReturnBy: 'September 7, 2020',
    productReview: true,
    productSupport: false,
    orderDescription: {
      numberOfItems: 1,
      name: ['JavaScript for impatient programmers'],
      itemCost: [31.55],
      producedBy: ['Dr. Axel Rauschmeyer'],
    },
  },
  {
    orderNumber: '113-998-4268-1280257',
    orderTotal: 44.53,
    orderShipTo: 'JS Masher',
    orderDate: 'July 19, 2020',
    orderDelivered: 'July 20, 2020',
    orderReturnBy: 'August 19, 2020',
    productReview: true,
    productSupport: false,
    orderDescription: {
      numberOfItems: 1,
      name: ['The Timeless Way of Building'],
      itemCost: [41.33],
      producedBy: ['Alexander, Christopher'],
    },
  },
  {
    orderNumber: '114-2875557-9059409',
    orderTotal: 17.22,
    orderShipTo: 'JS Masher',
    orderDate: 'July 4, 2020',
    orderDelivered: 'July 7, 2020',
    orderReturnBy: 'August 5, 2020',
    productReview: true,
    productSupport: false,
    orderDescription: {
      numberOfItems: 1,
      name: [
        'Gamecube Controller Adapter. Super Smash Bros Switch Gamecube Adapter for WII U, PC. Support Turbo and Vibration Features. No Driver and No Lag-Gamecube Adapter',
      ],
      itemCost: [15.98],
      producedBy: ['N/A'],
    },
  },
  {
    orderNumber: '113-2883177-2648248',
    orderTotal: 138.93,
    orderShipTo: 'JS Masher',
    orderDate: 'July 3, 2020',
    orderDelivered: 'July 5, 2020',
    orderReturnBy: 'August 4, 2020',
    productReview: true,
    productSupport: true,
    orderDescription: {
      numberOfItems: 2,
      name: [
        'GameCube Controller - Super Smash Bros. Edition (Nintendo Switch)',
        'The Art of Sql',
      ],
      itemCost: [94.95, 33.99],
      producedBy: ['N/A', 'Stephane Faroult'],
    },
  },
];
